### ISSUE TITLE
Onboard NIKHEF storage element to Rucio

### ISSUE THREAD

**Issue by StevenCTimm** [DUNE/data-mgmt-ops#3]
I have E-mailed Jeff Templon who is the site lead at NIKHEF and have not heard back from him yet with the endpoints.

**Comment by StevenCTimm** [comment]
On 18/06/2020 16:03, Steven C Timm wrote:
> Hi Andrew--has there been any movement on enabling the DUNE storage
> element at NIKHEF?   Let me know.

Thanks for the reminder, I'd meant to do this earlier this week. The
dune storage in now setup on our dcache system. The server alias to use
is dune.dcache.nikhef.nl and the writable path for rucio data is:

/pnfs/nikhef.nl/data/dune/generic/rucio

The /dune/Role=Production fqan can write to this space and any other
fqans can read from it.

You can also write to the directory above,
/pnfs/nikhef.nl/data/dune/generic, if you want to store none rucio
controlled data. Total storage allocated to the
/pnfs/nikhef.nl/data/dune/generic directory and sub directories is
currently 295 TB.

There's also a file /pnfs/nikhef.nl/common/srr/storage-descriptor.json
on the dcache system that has json formatted storage resource records
for our various storage endpoints. Is has the total bytes assigned to
and used by each storage share and is updated hourly. In the file our
dune storage share is named dune-generic-pools.


Cheers,

Andrew

**Comment by wyuan-uoe** [comment]
I'm adding NIKHEF RSE, comes the follows RSE info:
```
Protocols:
==========
  davs
    extended_attributes: None
    hostname: dune.dcache.nikhef.nl
    prefix: /pnfs/nikhef.nl/data/dune/generic/rucio
    domains: {u'wan': {u'read': 1, u'write': 1, u'third_party_copy': 1, u'delete': 1}, u'lan': {u'read': 0, u'write': 0, u'delete': 0}}
    scheme: davs
    port: 2880
    impl: rucio.rse.protocols.gfalv2.Default
  gsiftp
    extended_attributes: None
    hostname: dune.dcache.nikhef.nl
    prefix: /pnfs/nikhef.nl/data/dune/generic/rucio
    domains: {u'wan': {u'read': 1, u'write': 1, u'third_party_copy': 1, u'delete': 1}, u'lan': {u'read': 0, u'write': 0, u'delete': 0}}
    scheme: gsiftp
    port: 2811
    impl: rucio.rse.protocols.gfalv2.Default
  root
    extended_attributes: None
    hostname: dune.dcache.nikhef.nl
    prefix: /pnfs/nikhef.nl/data/dune/generic/rucio
    domains: {u'wan': {u'read': 1, u'write': 1, u'third_party_copy': 1, u'delete': 1}, u'lan': {u'read': 0, u'write': 0, u'delete': 0}}
    scheme: root
    port: 0
    impl: rucio.rse.protocols.gfalv2.Default
```

When I test to add a duplicate rule to move a dataset to NIKHEF, all tans are failed. From FTS monitoring, the errors are:
```
xrootd:
TRANSFER [42] Error on XrdCl::CopyProcess::Run(): [FATAL] Auth failed: (destination)
or
TRANSFER [13] Failed to stat file (Permission denied)

gsiftp:
TRANSFER [70] TRANSFER globus_ftp_client: the server responded with an error 530 Login denied
```

Simply `xrdcp` test files to NIKHEF /panfs path can work.
